DOC-3396: Update Callback tutorial
MyPureCloud/developercenter-tutorials pull request #64
Opened 2021-06-22 03:38 UTC by PrinceMerluza

Update the tutorial for Callback ANI feature

2021-06-22 08:54 UTC, ronanwatkins approved these changes

2021-06-22 14:57 UTC, timsmithgenesys commented
Thanks for updating! Make sure you update the config.yml file with the new line numbers as well.

2021-06-22 14:57 UTC, timsmithgenesys requested changes
Thanks for updating! Make sure you update the config.yml file with the new line numbers as well.

2021-06-23 02:13 UTC, PrinceMerluza commented
Ah, thanks for catching that. Slipped my mind. Line highlights should now be updated as well.

2021-06-23 14:02 UTC, timsmithgenesys approved these changes

2021-06-23 14:02 UTC, merged